### ISSUE TITLE
REGISTRO TAQUILLEROS O PROMOTORES

### ISSUE THREAD

**Issue by eliyya** [mael098/appcine#14]
crear un apartado donde le permita al taquillero o promotor registrarse, el apartado del registro debe de asignar un rol, ya sea promotor o seller, donde guarde su nombre, y donde se le asigne un correo y una contraseña.

**Comment by AngelesTeaa** [comment]
Vista del registro, cabe aclarar que se mantiene tener una idea de un switch para que cuando se pase el puntero o se seleccione el rol quede sombreado
https://www.figma.com/file/45yb2IlQTxmqvZNt8H9CsZ/Vista?type=design&node-id=0%3A1&mode=design&t=Sdr0vgjUO89rpXhs-1

**Comment by eliyya** [comment]
el registro de promotores se debe cambiar a empleados
