### ISSUE TITLE
MENU DINAMICO DEFINIDO POR PARAMETROS.

### ISSUE THREAD

**Issue by eliyya** [mael098/appcine#15]
crear un menu donde este ubicado entre las vistas de administrador, donde en este menu, nos permita ver el logo del cine, las opciones(en las cuales estarán definidas/indicadas por parámetros) un exit que sera un cierre de sesión, y también un menu desplegable, en el cual su función sera cambiar de rol, es decir, le permita ver como actúa el promotor, taquillero, etc.
(cualquier cambio hacerlo saber, si no haga caso omiso).

**Comment by AngelesTeaa** [comment]
Visualización de las vistas incluyendo en las mismas el menu desplegable, en la seccion de opciones por el momento estan las que son para el administrador, a la hora de programarlos se definirán por parámetros.

https://www.figma.com/file/45yb2IlQTxmqvZNt8H9CsZ/Vista?type=design&node-id=0%3A1&mode=design&t=m6M1QiBx5roc0aXm-1
