### ISSUE TITLE
Idea Principal.

### ISSUE THREAD

**Issue by pedrogutierritos28** [mael098/appcine#4]
Implementar las diversas peliculas que se implementaran en cartelera, al momento de dar el click en dicha pelicula que se desea ver, debe aparecer las funciones que se estaran proyectando en dicha hora del dia, el idioma en que estara, el tipo de proyeccion que tendra (IMAX, MACRO XE, 4DX, VIP, etc) el formato (ya sea 2D o 3D), la sucursal en donde estara. Momentaneamente es todo.

**Comment by AngelesTeaa** [comment]
Ventana de inicio y salas habilitadas:
https://www.figma.com/file/aWLgVTDbjPCnYUAXcen9eG/Prototipo?type=design&node-id=0%3A1&mode=dev&t=HYtaNIgdz813irtH-1

**Comment by eliyya** [comment]
La base de datos se inicio con las peliculas en [0c92989](https://github.com/mael098/appcine/pull/6/commits/0c92989fe6d333d9653f36125cb334499119d009) pero hasta ahora solo tiene 3 campos
![image](https://github.com/mael098/appcine/assets/62972439/8442b754-dd42-43bf-8525-681f754d885d)
Que mas necesita almacenar una pelicula?

**Comment by pedrogutierritos28** [comment]
![mejorada parte dos base de datos](https://github.com/mael098/appcine/assets/158686547/a9f022c6-edc4-4ef2-b555-77659bcc55d3)
ejemplo de base de datos que puede llevar en un cine/cartelera, no necesidad poner todo, solo sugerencia

**Comment by eliyya** [comment]
Asi quedo
![image](https://github.com/mael098/appcine/assets/62972439/53f79500-d15e-4327-a3f5-5e1de1c81953)
